#if !canImport(ObjectiveC)
import XCTest

extension ObjectStoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ObjectStoreTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ObjectStoreTests.__allTests__ObjectStoreTests),
    ]
}
#endif
